### ISSUE TITLE
Taking `isolation: isolate` (and more generally reseting the stacking context) in account

### ISSUE THREAD

**Issue by Adzetko** [ginpei/devtools-z-index#89]
First, this is a super useful plugin. It made debugging navbars and fullscreen menus so much easier.

Well, until I found out about `isolation: isolate`, which basically makes z-index containers. I'd love to see some "grouping" in this plugin's UI, depending if stacking context has been reset by some parent element (and which property causes it, because `isolation: isolate` is far from being the only CSS property to reset the stacking context, and the confusing part is often that you have some properties doing it without your knowledge about this).

I don't really know how you have implemented z-index detection, and how much work would be involved to add such a feature, so I'd totally understand if this gets closed without further ado.

**Comment by Adzetko** [comment]
Oh well I just read you suggested it yourself on the readme of the plugin, I should have read readme 🤦

**Comment by ginpei** [comment]
Thank you for your feedback! The grouping feature would indeed be a valuable addition. While I won't be able to begin work on it immediately, I'll certainly remember that this feature has been requested.
