### ISSUE TITLE
Migrate to Manifest V3

### ISSUE THREAD

**Issue by ginpei** [ginpei/devtools-z-index#90]
Chrome

- [Manifest V2 support timeline  |  Extensions  |  Chrome for Developers](https://developer.chrome.com/docs/extensions/develop/migrate/mv2-deprecation-timeline)
- [Extensions / Manifest V3  |  Chrome for Developers](https://developer.chrome.com/docs/extensions/develop/migrate/what-is-mv3)

Firefox

- [Manifest V3 migration guide | Firefox Extension Workshop](https://extensionworkshop.com/documentation/develop/manifest-v3-migration-guide/)

**Comment by nishith142** [comment]
> - [Manifest V2 support timeline  |  Extensions  |  Chrome for Developers](https://developer.chrome.com/docs/extensions/develop/migrate/mv2-deprecation-timeline)
> 
> - [Extensions / Manifest V3  |  Chrome for Developers](https://developer.chrome.com/docs/extensions/develop/migrate/what-is-mv3)

@ginpei
